#!/usr/bin/python

import OvhApi
import key

key = key.key()
AK = key.appkey
AS = key.appsec

api = OvhApi.Api("https://eu.api.ovh.com/1.0", AK, AS)
accessRules = [{"method": "GET", "path": "/*"}, {"method": "PUT", "path": "/*"}]
credential = api.requestCredential(accessRules)
print credential
