#!/usr/bin/python
# coding=utf-8

# Copyright 2014 Hubert Godfroy

# This file is part of dynovh.

# dynovh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# dynovh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with dynovh.  If not, see <http://www.gnu.org/licenses/>


import domains
import handler

__author__ = 'hubert'

domains = domains.domains()
dyndoms = domains.domlist

handler.process_zone (dyndoms)

