#!/bin/bash

# Copyright 2014 Hubert Godfroy

# This file is part of dynovh.

# dynovh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# dynovh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with dynovh.  If not, see <http://www.gnu.org/licenses/>

# OVH - DynHost
#
# Permet de mettre à jour le champ DYNHOST
# pour votre nom de domaine.
# Utilise l'adresse de l'interface ppp0 de 
# votre système Linux.

# La mise à jour ne se fait que si l'adresse IP
# a effectivement changé.
# Fichier de log: dynhost.log

p1=$(pwd)
cmd=$0
p2=${cmd/dynhost/}
cd $p1
cd $p2

HOST=$(cat host)
LOGIN=$(cat login)
PASSWORD=$(cat password)
#OPTIONS="-r checkip.dyndns.org -v" # add verbosity
OPTIONS="-r checkip.dyndns.org"

#echo ---------------------------------- >> ./dynhost.log
#echo `date` >> ./dynhost.log 
#echo Démarrage de DynHost >> ./dynhost.log

python ipcheck.py $OPTIONS $LOGIN $PASSWORD $HOST
