#!/bin/bash

# OVH - DynHost
#
# Permet de mettre à jour le champ DYNHOST
# pour votre nom de domaine.
# Utilise l'adresse de l'interface ppp0 de 
# votre système Linux.

# La mise à jour ne se fait que si l'adresse IP
# a effectivement changé.
# Fichier de log: dynhost.log

p1=$(pwd)
cmd=$0
p2=${cmd/dynhost/}
cd $p1
cd $p2

HOST=$(cat host)
LOGIN=$(cat login)
PASSWORD=$(cat password)
#OPTIONS="-r checkip.dyndns.org -v" # add verbosity
#OPTIONS="-r checkip.dyndns.org"
OPTIONS="-r checkip.pointfixe.fr"

#echo ---------------------------------- >> ./dynhost.log
#echo `date` >> ./dynhost.log 
#echo Démarrage de DynHost >> ./dynhost.log

python ipcheck.py $OPTIONS $LOGIN $PASSWORD $HOST
